baseurl = "https://williamtyoung.github.io"
title = "Bill Young"
languageCode = "en-us"
theme = "hugo-theme-minos"

[params]
    katex = true
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
