baseurl = "https://williamtyoung.github.io/"
title = "Bill Young"
languageCode = "en-us"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
    katex = true
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
